### ISSUE TITLE
Write article for PLoS Computational Biology on workflow management system evaluation

### ISSUE THREAD

**Issue by mikej888** [riboviz/workflows#1]

**Comment by mikej888** [comment]
@ewallace suggests:

> we should turn this into something published in a journal as well as or instead of the SSI blog. The PLoS Computational Biology education section would be ideal: https://journals.plos.org/ploscompbiol/s/other-article-types.
>
> I did a quick search and they don't have anything on selecting a workflow system that I've found.
> One article on Script of Scripts: https://doi.org/10.1371/journal.pcbi.1006843
> One on cloud computing that touches on workflows: https://doi.org/10.1371/journal.pcbi.1005994
> Another on neuroimaging that mentions snakemake: https://doi.org/10.1371/journal.pcbi.1007358
> Another on developing usable software, that briefly mentions workflows: https://doi.org/10.1371/journal.pcbi.1005265

> So my suggestion would be, first implement riboviz in nextflow, then return to write this up for submission to PLoS Comput biology education section? I'd happy to help write a slightly more general introduction and conclusion."

**Comment by mikej888** [comment]
Inspired by the "Ten Simple Rules...", "Eleven Quick Tips..." titles, we could adopt a title like "4 steps for choosing a bioinformatics workflow management system (or any software)" with structure Survey, Shortlist, Hands-on Evaluation (1), Select.  The article should emphasise this is not a recommendation Nextflow as a workflow management system in general but how we decided upon Nextflow based on our specific criteria.

We could blog about the article once published.

(1) or something beginning with S for alliteration.

**Comment by shahpr** [comment]
I think it is a great idea to convert many of the lessons learned with workflow management here into an education paper for PLOS Comp. However, I feel instead of explaining why settled on one workflow manager over others, it might make sense to explain WHEN different workflow managers should be used depending on use cases. For example:

1. If you work primarily in a single language environment should you pick a simple to learn workflow manager versus one with a steeper learning curve with added functionality that you may not use?
2. If you pan to distribute the code as a software package versus if all your code is for internal use only.

You also need to be cognizant about how the field of workflow managers are constantly evolving with added functionalities and how those might affect your choice.

**Comment by mikej888** [comment]
Explaining when different workflow managers should be used is a different focus from a process for how to choose a specific workflow manager. There may be a number of options available even within a specific class of workflow managers or satisfying a specific set of use cases in which case an example of a process as to how to choose between these can then be useful (a process which is applicable to myriad classes of software, not just workflow managers).

We have most the raw material for the latter article but we have very little raw material for the former and the idea behind an article was a "quick win". I don't think one article precludes the other.

Leipzig, Jeremy (2017) A review of bioinformatic pipeline frameworks. Briefings in Bioinformatics, Volume 18, Issue 3, 1 May 2017, Pages 530-536, https://doi.org/10.1093/bib/bbw020 has some general advice in "Choosing a pipeline framework".

**Comment by ewallace** [comment]
Mick Watson (Roslin Bioinformatics prof, who wrote the blogpost) and Alison Meynert (IGMM Bioinformatics head) are happy to comment on  draft/preprint of this article. They should be ideal audience.

**Comment by kavousan** [comment]
@mikej888 to deal with this after [#167](https://github.com/riboviz/riboviz/issues/167)

**Comment by ewallace** [comment]
Re: recommending editors. We will have to recommend the Education Editors, B. F. Francis Ouellette and Patricia Palagi, listed on the [PLoS Comput. Biol editorial board](https://journals.plos.org/ploscompbiol/s/editorial-board).

**Comment by mikej888** [comment]
Submitted to PLOS Comput Biol. and preprint submitted to bioRxiv.

**Comment by mikej888** [comment]
bioRxiv preprint:

* DOI: 10.1101/2020.08.04.236208
* Link https://biorxiv.org/cgi/content/short/2020.08.04.236208v1
* QR code: https://connect.biorxiv.org/qr/2020.08.04.236208

**Comment by mikej888** [comment]
Accepted conditional on revisions to address reviewers' comments.

**Comment by mikej888** [comment]
Submitted revised manuscript and response to reviewers.

**Comment by mikej888** [comment]
Revised version has been provisionally accepted. Awaiting information on formatting changes to be made for formal acceptance.

**Comment by mikej888** [comment]
An entry should be submitted to University of Edinburgh's research outputs database, PURE, within 3 months of publication. @ewallace can do this.

**Comment by mikej888** [comment]
Received latest version from copy editors for review.

**Comment by mikej888** [comment]
Final prepublication proof copy has been reviewed. Estimated publication date is 25/02.

**Comment by mikej888** [comment]
Created #5 for blog post advertising article when it's published.

**Comment by mikej888** [comment]
Published, Jackson, Michael; Kavoussanakis, Kostas; Wallace, Edward W.J. "Using prototyping to choose a bioinformatics workflow management system". PLOS Computational Biology, 25 February 2021. doi: [10.1371/journal.pcbi.1008622](https://doi.org/10.1371/journal.pcbi.1008622)
