### ISSUE TITLE
Contribute riboviz to nf-core?

### ISSUE THREAD

**Issue by ewallace** [riboviz/workflows#3]
As a long-term goal, if/when riboviz is implemented in nextflow, would we want to contribute it to the [nf-core](https://nf-co.re/) collection? Would increase discoverability/review/usability.

**Comment by mikej888** [comment]
See issue Explore how to contribute RiboViz Nextflow to nf-core riboviz/riboviz#175.

**Comment by mikej888** [comment]
Closed as now duplicated in riboviz/riboviz.

**Comment by kavousan** [comment]
We reject as it is a duplicate of riboviz/riboviz#175.
