### ISSUE TITLE
Write presentation for RiboViz conceptual meeting of 29/04/20

### ISSUE THREAD

**Issue by mikej888** [riboviz/workflows#4]

**Comment by mikej888** [comment]
Added to [gh-pages](https://github.com/riboviz/workflows/tree/gh-pages) branch, commit 7c689d6. See https://riboviz.github.io/workflows/.

**Comment by ewallace** [comment]
Note (slightly off-topic): @ewallace to invite WCB core bioinformatics colleagues to the presentation.
